# core

> BFrame

In [ ]:
#| default_exp core

In [ ]:
#| hide
from nbdev.showdoc import *

In [ ]:
#| export
from fastcore.all import *
from basedpl import *
from math import inf

In [ ]:
#| export
class BFrame(Array):
    def __init__(self, arr): super().__init__(arr)
    def _classify(self): pass # TODO Update BasedPL to simplify subclassing of Array.
    # TODO Update BasedPL result_ to allow simple method chaining in BFrame

In [ ]:
test_frame = BFrame([1,2,3])
test_frame

[1 2 3]ₓ

In [ ]:
test_eq(BFrame, type(test_frame))

In [ ]:
#| export
@patch(cls_method=True)
def read_csv(cls:Array, path, **kwargs): return cls(csv(nget(path, **kwargs)))

In [ ]:
bf = BFrame.read_csv("../data/toy.csv", encoding="UTF-8")
bf.df.head(3)

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No

In [ ]:
#| export
@patch
def save_csv(self:Array, path): return nput(path, csv.undo(self))

In [ ]:
# bf.save_csv("../data/save_test.csv");

In [ ]:
#| export
@patch
def take(self:BFrame, n:int): return take.each(n, self)

In [ ]:
bf.take(2).df

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No

In [ ]:
#| export
@patch
def head(self:BFrame, n=5): return self.take(n)

In [ ]:
bf.head().df

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [ ]:
#| export
@patch
def tail(self:BFrame, n=5): return self.take(-n)

In [ ]:
bf.tail().df

   Number    City  Gender  Age    Income Illness
0  149996  Austin    Male   48   93669.0      No
1  149997  Austin    Male   25   96748.0      No
2  149998  Austin    Male   26  111885.0      No
3  149999  Austin    Male   25  111878.0      No
4  150000  Austin  Female   37   87251.0      No

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()